# Generated by Django 5.2.4 on 2025-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Alimentation', 'Alimentation'), ('Transport', 'Transport'), ('Loisirs', 'Loisirs')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
