# Generated by Django 5.2.4 on 2025-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='FCFA', max_length=5),
        ),
    ]
