# Generated by Django 5.2.4 on 2025-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_profile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro (€)'), ('$', 'Dollar ($)'), ('FCFA', 'Franc CFA'), ('£', 'Livre (£)'), ('¥', 'Yen (¥)')], default='FCFA', max_length=5),
        ),
    ]
